In [1]:
import numpy as np

Створіть матрицю 3x3 та знайдіть визначник:

In [2]:
import numpy as np

# створюємо матрицю
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# знаходимо визначник
det_a = np.linalg.det(a)

print(det_a) # 0.0

#У цьому випадку визначник дорівнює 0, тому що матриця не має оберненої матриці (вона є виродженою).

0.0


Створіть два масиви однакового розміру та об'єднайте їх в один масив по стовпцях:

Для цього можна використати функцію concatenate() з бібліотеки NumPy з аргументом axis=1.

In [4]:
import numpy as np

# створюємо два масиви
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# об'єднуємо їх по стовпцях
c = np.concatenate((a.reshape(-1, 1), b.reshape(-1, 1)), axis=1)

print(c)
# [[1 4]
#  [2 5]
#  [3 6]]


[[1 4]
 [2 5]
 [3 6]]


In [7]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[7, 8], [9, 10], [11, 12]])

c = np.hstack((a, b))

print(c)

d = np.concatenate((a, b), axis=1)

print(d)


#Один зі способів - використати функцію hstack(). Наприклад, якщо ми маємо два масиви a і b розміром 3х2, то ми можемо їх об'єднати за допомогою наступного коду:

[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]
[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]


Створіть два масиви однакового розміру та об'єднайте їх в один масив по рядках:

In [ ]:
import numpy as np

# створюємо два масиви
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# об'єднуємо їх по рядках
c = np.concatenate((a, b))

print(c) # [1 2 3 4 5 6]


Створення масиву з 10 елементів та зміна значення кожного другого елемента на -1:

In [ ]:
import numpy as np

# Створення масиву з 10 елементів
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Зміна значення кожного другого елемента на -1
arr[1::2] = -1

print(arr)


Створення масиву з 5 елементів та зміна кожного елемента на його квадрат:

In [ ]:
import numpy as np

# Створення масиву з 5 елементів
arr = np.array([2, 4, 6, 8, 10])

# Зміна кожного елемента масиву на його квадрат
arr = np.square(arr)

print("Масив:", arr)


Створення масиву з 20 випадкових дробових чисел та знаходження стандартного відхилення:

In [ ]:
import numpy as np

# Створення масиву з 20 випадкових дробових чисел в діапазоні від 0 до 1
arr = np.random.rand(20)

# Знаходження стандартного відхилення масиву
std_dev = np.std(arr)

print("Масив:", arr)
print("Стандартне відхилення:", std_dev)


Створення масиву з 10 випадкових цілих чисел та знаходження медіани:

In [ ]:
import numpy as np

# Створення масиву з 10 випадкових цілих чисел в діапазоні від 1 до 100
arr = np.random.randint(1, 101, 10)

# Знаходження медіани масиву
median = np.median(arr)

print("Масив:", arr)
print("Медіана:", median)


Масив з 5 елементів, відсортований в порядку зростання та в порядку спадання:

In [8]:
import numpy as np

arr = np.array([5,2,4,1,3])

sorted_arr_asc = np.sort(arr)
sorted_arr_desc = np.sort(arr)[::-1]

print("Відсортований масив в порядку зростання: ", sorted_arr_asc)
print("Відсортований масив в порядку спадання: ", sorted_arr_desc)


Відсортований масив в порядку зростання:  [1 2 3 4 5]
Відсортований масив в порядку спадання:  [5 4 3 2 1]


Функція, яка бере на вхід масив та повертає середнє арифметичне значення його елементів:

In [ ]:
import numpy as np

def mean(arr):
    return np.mean(arr)

arr = np.array([1,2,3,4,5])

mean_val = mean(arr)

print("Середнє значення: ", mean_val)


Функція, яка бере на вхід два масиви та повертає їхній скалярний добуток:

In [ ]:
import numpy as np

def dot_product(arr1, arr2):
    return np.dot(arr1, arr2)

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

dot = dot_product(arr1, arr2)

print("Скалярний добуток: ", dot)


Функція, яка бере на вхід масив та повертає максимальне та мінімальне значення в цьому масиві:

In [9]:
import numpy as np

def max_min(arr):
    return np.max(arr), np.min(arr)

arr = np.array([1,2,3,4,5])

max_val, min_val = max_min(arr)

print("Максимальне значення: ", max_val)
print("Мінімальне значення: ", min_val)


Максимальне значення:  5
Мінімальне значення:  1


Створення матриці 3x3 з випадковими дробовими числами в діапазоні від 0 до 1:

In [ ]:
import numpy as np

matrix = np.random.rand(3,3)

print(matrix)


Створення матриці 3x3 з випадковими цілими числами в діапазоні від 1 до 10:

In [ ]:
import numpy as np

matrix = np.random.randint(1, 10, size=(3,3))

print(matrix)


Створення NumPy масиву з 10 елементів, заповненого нулями та зміна першого елемента на 1:

In [ ]:
import numpy as np

arr = np.zeros(10)
arr[0] = 1

print(arr)


Створіть вектор довільної довжини та замініть всі його негативні значення на 0.

In [ ]:
import numpy as np

# Створення вектора довільної довжини
vector = np.array([1, -2, 3, -4, 5, -6, 7, -8, 9])

# Заміна негативних значень на 0
vector[vector < 0] = 0

print(vector)


Створіть матрицю розміром 4x4, заповніть її випадковими цілими числами в діапазоні від -5 до 5 та знайдіть ранг матриці.

In [10]:
import numpy as np

# Створення матриці розміром 4x4 з випадковими цілими числами в діапазоні від -5 до 5
matrix = np.random.randint(-5, 6, size=(4, 4))

# Знаходження рангу матриці
rank = np.linalg.matrix_rank(matrix)

print(matrix)
print("Ранг матриці: ", rank)


[[-1  4 -2 -5]
 [-3  0  5 -4]
 [-5 -4  5  2]
 [ 5 -1  0  5]]
Ранг матриці:  4


Створіть два вектори однакової довжини та знайдіть косинусний кут між ними.

In [11]:
import numpy as np

# Створення двох векторів однакової довжини
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Знаходження косинусного кута між векторами
cosine_angle = np.dot(vector1, vector2) / (np.linalg.norm(vector1) * np.linalg.norm(vector2))
angle_in_degrees = np.arccos(cosine_angle) * 180 / np.pi

print("Косинусний кут між векторами: ", cosine_angle)
print("Кут між векторами в градусах: ", angle_in_degrees)


Косинусний кут між векторами:  0.9746318461970762
Кут між векторами в градусах:  12.933154491899135


Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та обчисліть визначник матриці.

In [12]:
import numpy as np

# Створення матриці розміром 5x5 з випадковими дійсними числами в діапазоні від -1 до 1
matrix = np.random.uniform(-1, 1, size=(5, 5))

# Обчислення визначника матриці
determinant = np.linalg.det(matrix)

print(matrix)
print("Визначник матриці: ", determinant)


[[ 0.4289064   0.86159107 -0.98047772 -0.64349586 -0.26503284]
 [ 0.8476253   0.17193222 -0.09425275  0.79388439  0.27127396]
 [ 0.6237608  -0.74943075 -0.48338362  0.62382807  0.4313464 ]
 [-0.87602238  0.74002324  0.02087769 -0.15640416  0.77297594]
 [ 0.48727722  0.83141919 -0.2976064  -0.1167621   0.20356341]]
Визначник матриці:  0.45979161028817306


Створіть вектор довільної довжини та знайдіть середнє значення елементів, які перевищують задане порогове значення.

In [ ]:
import numpy as np

# Створення вектора з 10 випадкових чисел в діапазоні від 1 до 100
vec = np.random.randint(1, 101, size=10)

# Задання порогового значення
threshold = 50

# Знаходження елементів, які перевищують порогове значення
above_threshold = vec[vec > threshold]

# Знаходження середнього значення елементів, які перевищують порогове значення
mean_above_threshold = np.mean(above_threshold)

print(f"Вектор: {vec}")
print(f"Порогове значення: {threshold}")
print(f"Елементи, які перевищують порогове значення: {above_threshold}")
print(f"Середнє значення елементів, які перевищують порогове значення: {mean_above_threshold}")


Створіть матрицю розміром 3x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та розв'яжіть систему лінійних рівнянь Ax=b, де A - матриця, x - вектор невідомих, b - вектор вільних членів.

In [13]:
import numpy as np

A = np.random.rand(3,3)
b = np.random.rand(3)

x = np.linalg.solve(A, b)

print("A = ")
print(A)
print("b = ")
print(b)
print("x = ")
print(x)


A = 
[[0.75280953 0.14384081 0.39066931]
 [0.61996074 0.36869819 0.10009635]
 [0.13110424 0.14601349 0.9562345 ]]
b = 
[0.32221829 0.34153972 0.52788903]
x = 
[0.06912688 0.69146775 0.43698757]


Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх відношення.
(Для знаходження відношення двох матриць необхідно поділити їх елементи один на одного. Проте, для цього необхідно, щоб розміри матриць були однаковими. Отже, спочатку створимо дві матриці розміром 4x4 з випадковими цілими числами в діапазоні від 1 до 10 за допомогою модулю NumPy:)

In [14]:
import numpy as np

# Створення двох матриць розміром 4x4 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 10, (4, 4))
matrix2 = np.random.randint(1, 10, (4, 4))

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

# Знаходження відношення двох матриць
ratio = matrix1 / matrix2

print("Ratio:\n", ratio)



Matrix 1:
 [[9 3 6 4]
 [6 3 4 8]
 [5 2 4 6]
 [5 5 6 7]]
Matrix 2:
 [[5 7 6 4]
 [3 9 7 6]
 [1 3 4 2]
 [3 4 6 6]]
Ratio:
 [[1.8        0.42857143 1.         1.        ]
 [2.         0.33333333 0.57142857 1.33333333]
 [5.         0.66666667 1.         3.        ]
 [1.66666667 1.25       1.         1.16666667]]


Це значить, що елемент у першому рядку та першому стовпці матриці ratio є результатом ділення елементу у першому рядку та першому стовпці матриці matrix1 на елемент у першому рядку та першому стовпці матриці matrix2. Аналогічно для всіх інших елементів.

Створіть матрицю розміром 3x3 та замініть всі її елементи, що менші за середнє значення елементів матриці, на 0.

In [21]:
import numpy as np

# Створення матриці 3x3 з випадковими дійсними числами в діапазоні від 0 до 1
A = np.random.rand(3, 3)
print(A)

# Знаходження середнього значення елементів матриці
mean = np.mean(A)
print(f"Середнє значення = {mean}")

# Заміна елементів, що менші за середнє значення, на 0
A[A < mean] = 0

print(A)



[[0.28080729 0.42382192 0.64083804]
 [0.42274322 0.28035477 0.83162474]
 [0.95940803 0.12768783 0.08647566]]
Середнє значення = 0.4504179433197286
[[0.         0.         0.64083804]
 [0.         0.         0.83162474]
 [0.95940803 0.         0.        ]]


Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та обчисліть векторний добуток між ними.

In [25]:
import numpy as np

# Створення матриць 2x2 та 2x3 з випадковими цілими числами в діапазоні від 1 до 10
b = np.random.randint(1, 10, size=(2, 2))
c = np.random.randint(1, 10, size=(2, 3))

# Обчислення векторного добутку
d = np.dot(b, c)

print(d)


[[84 46 48]
 [79 26 41]]


Створіть вектор довільної довжини та знайдіть його норму (довжину).

In [26]:
import numpy as np

# Створення вектора довільної довжини з випадковими дійсними числами в діапазоні від 0 до 1
v = np.random.rand(5)

# Знаходження норми (довжини) вектора
norm = np.linalg.norm(v)

print(norm)


1.651384637308463


_____________________________________________________________________________________

Домашнє завдання №1

In [ ]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [ ]:
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [ ]:
a = np.zeros((3, 3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
a = np.random.randint(1, 11, (5,5))
print(a)

[[ 7 10  6  2 10]
 [ 7  9  4  2  8]
 [ 3  3  6  5  9]
 [10  8  3  5  1]
 [ 3  3  9  1  5]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
a = np.random.rand(4, 4)
print(a)

[[0.35448893 0.62348182 0.25158109 0.20567579]
 [0.51100877 0.36949712 0.22480539 0.86426348]
 [0.67691192 0.03815413 0.42832246 0.20885283]
 [0.48009991 0.53849911 0.56553487 0.62994907]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)

print("a = ", a)
print("b = ", b)

print("a + b = ", a + b)
print("a - b = ", a - b)
print("a * b = ", a * b)

a =  [6 2 2 9 6]
b =  [8 4 9 5 8]
a + b =  [14  6 11 14 14]
a - b =  [-2 -2 -7  4 -2]
a * b =  [48  8 18 45 48]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
a = np.random.randint(1, 11, size=7)
b = np.random.randint(1, 11, size=7)

dot_a_b = np.dot(a, b)

print("a = ", a)
print("b = ", b)
print("Скалярний добуток векторів дорівнює:", dot_a_b)

a =  [6 6 6 9 4 1 8]
b =  [ 3 10  9  3  5  2  9]
Скалярний добуток векторів дорівнює: 253


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
a = np.random.randint(1, 10, size=(2, 2))
b = np.random.randint(1, 10, size=(2, 3))

dot_a_b = np.dot(a, b)

print("a = ", a)
print("b = ", b)
print("Результат множення матриць:")
print(dot_a_b)

a =  [[7 1]
 [3 5]]
b =  [[3 1 1]
 [1 2 1]]
Результат множення матриць:
[[22  9  8]
 [14 13  8]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю. (Обернена матриця існує тільки для квадратних матриць, для яких детермінант не дорівнює нулю)

In [ ]:
a = np.random.randint(1, 11, size=(3, 3))
print("Вихідна матриця:")
print(a)

# перевірка, чи можна знайти обернену матрицю
if np.linalg.det(a) == 0:
    print("Матриця не має оберненої матриці.")
else:
    # знаходження оберненої матриці
    inv_a = np.linalg.inv(a)
    print("Обернена матриця:")
    print(inv_a)


Вихідна матриця:
[[3 1 3]
 [5 8 7]
 [6 4 1]]
Обернена матриця:
[[ 0.18691589 -0.10280374  0.1588785 ]
 [-0.34579439  0.14018692  0.05607477]
 [ 0.26168224  0.05607477 -0.17757009]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
a = np.random.rand(4, 4)
print(a)

a_transp = np.transpose(a)
print("Транспонована матриця:")
print(a_transp)

[[0.87298873 0.32313631 0.84631268 0.70152019]
 [0.92968705 0.08546864 0.14092307 0.76525695]
 [0.12001872 0.22090021 0.28490696 0.32351804]
 [0.68992537 0.84135905 0.93096108 0.28223114]]
Транспонована матриця:
[[0.87298873 0.92968705 0.12001872 0.68992537]
 [0.32313631 0.08546864 0.22090021 0.84135905]
 [0.84631268 0.14092307 0.28490696 0.93096108]
 [0.70152019 0.76525695 0.32351804 0.28223114]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [ ]:
matr = np.random.randint(1, 10, size=(3, 4))
vect = np.random.randint(1, 10, size=4)
print("Матриця:")
print(matr)
print("Вектор:")
print(vect)

print("Результат множення матриці на вектор:")
result = np.dot(matr, vect)
print(result)

Матриця:
[[8 3 7 6]
 [9 8 8 7]
 [9 7 3 6]]
Вектор:
[9 2 3 3]
Результат множення матриці на вектор:
[117 142 122]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [ ]:
matr = np.random.rand(2, 3)
vect = np.random.rand(3)
print("Матриця:")
print(matr)
print("Вектор:")
print(vect)

print("Результат множення матриці на вектор:")
result = np.dot(matr, vect)
print(result)

Матриця:
[[0.69817495 0.66957257 0.0633264 ]
 [0.94132088 0.70192663 0.98405776]]
Вектор:
[0.97630631 0.55499514 0.06980454]
Результат множення матриці на вектор:
[1.0576626  1.37727509]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [ ]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print("Перша матриця:")
print(a)
print("Друга матриця:")
print(b)

print("Поелементне множення через multiply:")
result = np.multiply(a, b)
print(result)
print("Поелементне множення через *:")
print(a*b)

Перша матриця:
[[5 4]
 [1 6]]
Друга матриця:
[[6 4]
 [1 8]]
Поелементне множення через multiply:
[[30 16]
 [ 1 48]]
Поелементне множення через *:
[[30 16]
 [ 1 48]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [ ]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print("Перша матриця:")
print(a)
print("Друга матриця:")
print(b)

print("Добуток матриць:")
result = np.dot(a, b)
print(result)

Перша матриця:
[[5 8]
 [1 5]]
Друга матриця:
[[10  4]
 [ 6 10]]
Добуток матриць:
[[ 98 100]
 [ 40  54]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [ ]:
a = np.random.randint(1, 101, size=(5, 5))
sum_a = np.sum(a)
print("Матриця")
print(a)
print("Сума елементів матриці:")
print(sum_a)

Матриця
[[33 35 46 98  3]
 [35 26 67 92 30]
 [15 56 56 68 26]
 [64 95 21  6  2]
 [66 13 91  9 42]]
Сума елементів матриці:
1095


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [ ]:
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))
print("Перша матриця:")
print(a)
print("Друга матриця:")
print(b)

result = a - b
print("Різниця матриць:")
print(result)

Перша матриця:
[[ 5  3  5  7]
 [ 9  5  3  2]
 [ 1  7  6  6]
 [ 6  9 10  9]]
Друга матриця:
[[ 6  2 10  3]
 [ 9  4  7  3]
 [ 7  1  7  6]
 [ 2  9  8  5]]
Різниця матриць:
[[-1  1 -5  4]
 [ 0  1 -4 -1]
 [-6  6 -1  0]
 [ 4  0  2  4]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [ ]:
a = np.random.rand(3, 3)
print("Матриця:")
print(a)

# Обчислення сум елементів кожного рядка матриці
row_sums = a.sum(axis=1)

# Перетворення одновимірного масиву на вектор-стовпчик
col_vec = row_sums.reshape((-1, 1))

print("Вектор-стовпчик з сумами елементів кожного рядка:")
print(col_vec)

Матриця:
[[0.93691243 0.87759296 0.8300773 ]
 [0.10116688 0.39740299 0.30359529]
 [0.44538679 0.20820476 0.64165348]]
Вектор-стовпчик з сумами елементів кожного рядка:
[[2.64458269]
 [0.80216515]
 [1.29524503]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел. 

In [ ]:
a = np.random.randint(1, 11, size=(3, 4))
print("Матриця:")
print(a)

print("Квадрати значень матриці:")
squares = np.power(a, 2)
print(squares)

Матриця:
[[ 2  3  9 10]
 [ 8  4  9  7]
 [ 6  8  8  9]]
Квадрати значень матриці:
[[  4   9  81 100]
 [ 64  16  81  49]
 [ 36  64  64  81]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [ ]:
vect = np.random.randint(1, 50, size=4)
print("Вихідний вектор", vect)

sqrt_vect = np.sqrt(vect)
print("Вектор з квадратими коренями:", sqrt_vect)

Вихідний вектор [10 20 18 19]
Вектор з квадратими коренями: [3.16227766 4.47213595 4.24264069 4.35889894]
